# Generated by Django 5.2.5 on 2025-08-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subtask',
            table='subtask',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='tasklist',
            table='tasklist',
        ),
    ]
